
echo '/* This file is automatically generated by spr_enum.sh */' >spr_enum.h
echo '#define SPRITE_ENUM(X) \' >>spr_enum.h

for x in player azmagelle
do
 awk -F' ' '$1 ~ /^[A-Za-z_][A-Za-z_0-9]*$/ { print "X(" $1 "),\\" }' textures/$x.png.txt >>spr_enum.h
done

echo 'X(sprite_enum_unused)' >>spr_enum.h

